---
abstract: 'Base class for exceptions'
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  Test::More: '0'
  Test::Warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-Exception-Base
requires:
  Carp: '0'
  Moose: '0'
  Moose::Role: '0'
  overload: '0'
  strict: '0'
  version: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=MooseX-Exception-Base
  homepage: https://github.com/ivanwills/MooseX-Exception-Base
  repository: https://github.com/ivanwills/MooseX-Exception-Base.git
version: 0.0.6
